version: '3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_foodgram:/backend_static/
      - media_foodgram:/app/media/
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_foodgram:/frontend_static
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_foodgram:/static/
      - media_foodgram:/app/media/