@users = http://127.0.0.1:8000/api/users/
@user_me = http://127.0.0.1:8000/api/users/me/
@user = http://127.0.0.1:8000/api/users/3/
@user_subscribe = http://127.0.0.1:8000/api/users/2/subscribe/
@user_subscription = http://127.0.0.1:8000/api/users/subscriptions/
@get_token = http://127.0.0.1:8000/api/auth/token/login/
@remove_token = http://127.0.0.1:8000/api/auth/token/logout/
@tags = http://127.0.0.1:8000/api/tags/
@tag = http://127.0.0.1:8000/api/tags/1/
@ingredients = http://127.0.0.1:8000/api/ingredients/
@ingredient = http://127.0.0.1:8000/api/ingredients/1/
@recipes = http://127.0.0.1:8000/api/recipes/
@recipe = http://127.0.0.1:8000/api/recipes/2/
@favorite = http://127.0.0.1:8000/api/recipes/2/favorite/
@shopping_cart = http://127.0.0.1:8000/api/recipes/2/shopping_cart/
@download_shopping_cart = http://127.0.0.1:8000/api/recipes/download_shopping_cart/


###
POST {{ users }} HTTP/1.1
Content-Type: application/json

{
  "email": "vpupkin111@yandex.ru",
  "username": "vasya.pupkin111",
  "first_name": "Вася111",
  "last_name": "Пупкин111",
  "password": "Qwerty123ewq321"
}

###
POST {{ get_token }} HTTP/1.1
Content-Type: application/json

{
    "password": "Qwerty123ewq321",
    "email": "vpupkin111@yandex.ru"
}

###
POST {{ remove_token }} HTTP/1.1
Content-Type: application/json
authorization: Token 67c4bd73245fcf8a8e13689f9802e2ced26a8d7e

{

}

###
GET {{ users }} HTTP/1.1
content-type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
GET {{ user }} HTTP/1.1
content-type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
GET {{ user_me }} HTTP/1.1
content-type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be


###
POST {{user_subscribe}} HTTP/1.1
Content-Type: application/json
Authorization: Token e74fb769c85d88f92103c09737c43f6c082813c6

{
  
}

###
DELETE {{user_subscribe}} HTTP/1.1
Content-Type: application/json
Authorization: Token e74fb769c85d88f92103c09737c43f6c082813c6

{
  
}

###
GET {{ user_subscription }} HTTP/1.1
content-type: application/json
Authorization: Token e74fb769c85d88f92103c09737c43f6c082813c6

###
GET {{tag}} HTTP/1.1
Content-Type: application/json

###
GET {{tags}} HTTP/1.1
Content-Type: application/json

###
GET {{ingredient}} HTTP/1.1
Content-Type: application/json

###
GET {{ingredients}} HTTP/1.1
Content-Type: application/json

###
GET {{recipes}} HTTP/1.1
Content-Type: application/json

###
GET {{recipe}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
GET {{recipe}} HTTP/1.1
Content-Type: application/json

###
POST {{recipes}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

{
  "tags": [1],
  "ingredients": [
    {
      "id": 1,
      "amount": 2
    },
    {
      "id": 2,
      "amount": 3
    }
  ],
  "name": "apitest",
  "image": null,
  "text": "apitest",
  "cooking_time": 10
}

###
PATCH {{recipe}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

{
  "tags": [1],
  "ingredients": [
    {
      "id": 1,
      "amount": 2
    },
    {
      "id": 2,
      "amount": 3
    }
  ],
  "image": null,
  "text": "apitest",
  "cooking_time": 10
}

###
PATCH {{recipe}} HTTP/1.1
Content-Type: application/json
Authorization: Token e74fb769c85d88f92103c09737c43f6c082813c6

{
  "tags": [1],
  "ingredients": [
    {
      "id": 1,
      "amount": 2
    },
    {
      "id": 2,
      "amount": 3
    }
  ],
  "name": "apitest",
  "image": null,
  "text": "apitest",
  "cooking_time": 10
}

###
DELETE {{recipe}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
POST {{favorite}} HTTP/1.1
Content-Type: application/json
Authorization: Token e74fb769c85d88f92103c09737c43f6c082813c6 

###
DELETE {{favorite}} HTTP/1.1
Content-Type: application/json
Authorization: Token e74fb769c85d88f92103c09737c43f6c082813c6

###
POST {{shopping_cart}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
DELETE {{shopping_cart}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
GET {{download_shopping_cart}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be
