@users = http://127.0.0.1:8000/api/users/
@user = http://127.0.0.1:8000/api/users/2/
@get_token = http://127.0.0.1:8000/api/auth/token/login/
@remove_token = http://127.0.0.1:8000/api/auth/token/logout/
@tags = http://127.0.0.1:8000/api/tags/
@tag = http://127.0.0.1:8000/api/tags/1/
@ingredients = http://127.0.0.1:8000/api/ingredients/
@ingredient = http://127.0.0.1:8000/api/ingredients/1/
@recipes = http://127.0.0.1:8000/api/recipes/
@recipe = http://127.0.0.1:8000/api/recipes/1/
@favorite = http://127.0.0.1:8000/api/recipes/1/favorite/


###
POST {{ users }} HTTP/1.1
Content-Type: application/json

{
  "email": "vpupkin1@yandex.ru",
  "username": "vasya.pupkin1",
  "first_name": "Вася1",
  "last_name": "Пупкин1",
  "password": "Qwerty123ewq321"
}

###
POST {{ get_token }} HTTP/1.1
Content-Type: application/json

{
    "password": "Qwerty123ewq321",
    "email": "vpupkin1@yandex.ru"
}

###
POST {{ remove_token }} HTTP/1.1
Content-Type: application/json
authorization: Token 44184086db4ee6cc2e70c6efbae0e960dc2b0afe

{

}

###
GET {{ users }} HTTP/1.1
content-type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
GET {{ user }} HTTP/1.1
content-type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
GET {{tag}} HTTP/1.1
Content-Type: application/json

###
GET {{tags}} HTTP/1.1
Content-Type: application/json

###
GET {{ingredient}} HTTP/1.1
Content-Type: application/json

###
GET {{ingredients}} HTTP/1.1
Content-Type: application/json

###
GET {{recipes}} HTTP/1.1
Content-Type: application/json

###
GET {{recipe}} HTTP/1.1
Content-Type: application/json

###
POST {{recipes}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

{
  "tags": [1],
  "ingredients": [1],
  "name": "apitest",
  "image": null,
  "text": "apitest",
  "cooking_time": 10
}

###
DELETE {{recipe}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be

###
POST {{favorite}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be 

###
DELETE {{favorite}} HTTP/1.1
Content-Type: application/json
Authorization: Token 9d64e4c58e6da90a9adb729eb3a241a3c13f83be