# Generated by Django 3.2.3 on 2023-07-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230707_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Укажите описание блюда', null=True, verbose_name='Описание блюда'),
        ),
    ]
