# Generated by Django 3.2.3 on 2023-07-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230702_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='FollowingUser',
        ),
    ]
