# Generated by Django 3.2.3 on 2023-07-06 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_followinguser_followingauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Required. 150 characters or fewer.Letters, digits and @/./+/-/_ only.', regex='^[\\w.@+-]+\\Z')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Required. 150 characters or fewer.Letters, digits and @/./+/-/_ only.', regex='^[\\w.@+-]+\\Z')]),
        ),
    ]
